new changes

diff --git a/tbox-scan b/tbox-scan
--- a/tbox-scan
+++ b/tbox-scan
@@ -64,9 +64,8 @@ while getopts 'f:o:ilmvsh' flag; do
   esac
 done
 
-echo $input_file
-echo $output_file
-
 
 #Try running using either python or python3
-python3 -m tboxscan.tboxscnr.py $input_file $output_file $model $infernal_out $log_file $verbose $silence ||echo Error: T-box scanning pipeline failed. Check proper usage, dependencies, and auxilliary files. && print_usage
+python3 -m tboxscan.tboxscnr $input_file $output_file $model $infernal_out $log_file $verbose $silence
+
+#||echo Error: T-box scanning pipeline failed. Check proper usage, dependencies, and auxilliary files. && print_usage
